### ISSUE TITLE
Open new links in popups instead of tabs

### ISSUE THREAD

**Issue by BerkeAras** [nativefier/nativefier#1408] opened 2022-05-04 12:51 UTC
**Homework**

- [X] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md , no existing option fits my needs.
- [X] I searched existing issues, open & closed. Yes, my feature request is new.
- [X] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Problem statement**

Nativefier should get the option to open new links in new windows instead of opening in new tabs.

**Suggested solution**

A new config-option.

**Alternative solutions**

N/A

**Context**

 - Nativefier: 47.0.0
 - Node.js: 16.14.0
 - Npm: 8.5.2
 - OS: macOS Monterey 12.3

**Comment by thomasbachem** [comment] 2022-08-08 13:46
Duplicate of #1310

**Comment by ronjouch** [comment] 2022-08-08 14:34
@thomasbachem indeed, thanks.

@BerkeAras with that, closing this issue, feel free to follow #1310.

**Closed by ronjouch** 2022-08-08 14:34 UTC
Labels: feature-request

**Comment by BerkeAras** [comment] 2022-08-27 15:58
Omg, I did not even know, that I created an issue a while ago 😂  @ronjouch
