### ISSUE TITLE
I cannot run the Desktop app repeatedly

### ISSUE THREAD

**Issue by Oleg26Dev** [nativefier/nativefier#1462] opened 2022-09-15 09:55 UTC
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my bug is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Nativefier command

>nativefier 'localhost:7042'

### Steps to reproduce

I have built the Desktop app, run it - it works fine. 
But after it: run, exit, run, exit, run and see "Loading..." only in the main window and cannot run the app again as a full functional app.
What I do wrong? 

### Expected behavior

It should be run repeatedly

### Actual behavior

I have built the Desktop app, run it - it works fine. 
But after it: run, exit, run, exit, run and see "Loading..." only in the main window and cannot run the app again as a full functional app.

### Nativefier version

49.01

### Node.js version

v16.16.0

### npm version

8.19.2

### OS

Windows 10

**Comment by Oleg26Dev** [comment] 2022-09-15 10:54
Additional info about miracles:
1. I have made my Blazor site in VS 2022. 
2. >nativefier 'https://localhost:7062'
3. If I run in the VS the site, Opera appears with site then I run the Desktop app it can be run repeatedly, not always but can be
4. If VS is closed then I cannot run app.exe : it appears as an app with blank window
5. I run VS again and run the site. Now app.exe can be run

**Comment by TheCleric** [comment] 2022-09-15 15:00
I think this may be a misunderstanding of what Nativefier does. Nativefier does not save a copy of the site you pass to it in the app. It essentially just runs as a web browser that only serves one page (the one you pass to it).

Therefore if the web site you pass it goes away (such as when you close Visual Studio, which is running as your web server), then the app will no longer be able to access the page. Thus you'll only see "Loading" as it attempts to, unsuccessfully, contact the web server that is not there anymore.

Closing as this is all by design. If you think I'm misunderstanding your situation, you can provide more context and we may reopen.

**Closed by TheCleric** 2022-09-15 15:00 UTC
Labels: bug

**Comment by Oleg26Dev** [comment] 2022-09-16 09:12
Oh, I thought it works like Electron.NET - builds Desktop app independent on the source site.
But how to be: I want to create Desktop app from a site and provide it to my customer. He has the app-> db server, i.e. all what he needs to work. I should provide web site too?

**Comment by Oleg26Dev** [comment] 2022-09-23 09:02
Any answers? thank you
