### ISSUE TITLE
Instagram custom icon is overridden by auto-detected / lower resolution extracted icon

### ISSUE THREAD

**Issue by vishnuraghavb** [nativefier/nativefier#806] opened 2019-05-19 16:27 UTC
### Description

I'm trying to use a custom icon for www.instagram.com nativefier app, but the built app doesn't apply my custom icon but reverts back to the default Instagram icon.

But, under 'instagram-linux-x64/resources/app/', I can see my custom icon as "icon.png". I have also tried deleting the app folder in '~/.config/' and built the app again but same issue persists.

I have build few WhatsApp webapps using nativefier with custom icon and had no issues.

Please help me with this issue. Thanks!

### Steps to reproduce issue

1. Get an icon for testing. In my case I used a 32px x 32px custom icon in ".png" format(since I'm on a Linux machine) located in my '~/Pictures/' folder.
2. Build the nativefier app using the below mentioned command.
3. Open the app and check the tray icon. 

### Details

- Are you nativefying a *public* website? Yes, www.instagram.com
- Feature request? No. Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes.
- Full nativefier command used to build your app: `nativefier www.instagram.com --user-agent "Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36" --icon "~/Pictures/icon.png" --tray --name "Instagram" --width "360px" --height "640px" --counter --single-instance`
- Version of Nativefier (run `nativefier --version`): `v7.6.12`
- Version of node.js (run `node --version`): `v11.15.0`
- OS: `Manjaro Linux x86_64`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ahmedu007** [comment] 2019-05-20 10:18
Have you tried it with `.icns` file? It worked perfectly for other apps that I've used nativefier to convert

**Comment by vishnuraghavb** [comment] 2019-05-25 10:50
The API documentation doesn't insist to use `.icns` on Linux. Though, I tried what you have suggested. This time, the app doesn't even display a tray icon. :confused:

**Comment by yuuta-togashi** [comment] 2019-06-28 09:45
I have the same issue but with web whatsapp

**Comment by mxdpeep** [comment] 2019-08-21 10:41
I have used https://icoconvert.com/ to create an .ico file from PNG, application build in 10 secs. without errors

**Comment by mxdpeep** [comment] 2019-08-22 10:14
> Have you tried it with `.icns` file? It worked perfectly for other apps that I've used nativefier to convert

this is for Mac versions only!

**Comment by ronjouch** [comment] 2021-05-18 02:21
@vishnuraghavb @yuuta-togashi to recapitulate, your custom icon is overridden by the auto-detected / lower resolution extracted icon. Is this still an issue in the latest Nativefier?

**Comment by TheCleric** [comment] 2021-06-01 13:45
Closing for now since we haven't confirmed if this is still an issue. We will gladly reopen if it is still affecting users though.

**Closed by TheCleric** 2021-06-01 13:45 UTC
Labels: bug, need-info
