### ISSUE TITLE
Icon matching sometimes gets the wrong icon

### ISSUE THREAD

**Issue by champagnealexandre** [nativefier/nativefier#1278] opened 2021-09-10 04:37 UTC
**Homework**

- [X] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [X] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [X] I searched existing issues, open & closed. Yes, my bug is new.
- [X] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

This one is very simple: icon lookup for e.g. ```trainingpeaks.com``` wrongly matches the icon for ```ing```.

How can I override this behavior/prevent lookup in nativefier-icons?

**Steps to reproduce**

```nativefier www.trainingpeaks.com --name 'TrainingPeaks'``` gives:

```
...
Sanitized filename for TrainingPeaks : TrainingPeaks
Got 249 icons from gitcloud
Max icon match score: 1
Downloading https://nativefier.github.io/nativefier-icons/files/ing.png
...
```

**Expected behavior**

Not get the wrong icon :-)

**Actual behavior**

**Debug info**

**Context**

- Nativefier: 45.0.0
- Node.js: v14.17.3
- Npm: 6.14.13
- OS: Big Sur 11.5.2 (20G95)
- Additional context: none

**Comment by mattruzzi** [comment] 2021-09-11 19:19
Duplicate of #969 and #1125. 

You can use a custom image file on you system by using the `--icon` flag

https://github.com/nativefier/nativefier/blob/master/API.md#icon
#### [icon]

```
-i, --icon <path>
```

Notes:

- When packaging for Windows, must be a path to a `.ico` file.
- When packaging for Linux, must be a path to a `.png` file.
- When packaging for macOS, must be a `.icns` or a `.png` file if the [optional dependencies](../README.md#optional-dependencies) are installed.
  If your `PATH` has our image-conversion dependencies (`iconutil`, and either ImageMagick `convert` + `identify`, or GraphicsMagick `gm`), Nativefier will automatically convert the `.png` to a `.icns` for you.

Alternative to macOS users: [iConvertIcons](https://iconverticons.com/online/) can be used to convert `.pngs`, though it can be quite cumbersome.

To retrieve the `.icns` file from the downloaded file, extract it first and press File > Get Info. Then select the icon in the top left corner of the info window and press `⌘-C`. Open Preview and press File > New from clipboard and save the `.icns` file. It took me a while to figure out how to do that and question why a `.icns` file was not simply provided in the downloaded archive.

**Comment by mattruzzi** [comment] 2021-09-11 19:23
@ronjouch @TheCleric Since this seems to be a very common issue, we may just want to remove the ing logo from[ nativefier-icons](https://github.com/nativefier/nativefier-icons) until we get [nativefier-catalog](https://github.com/mattruzzi/nativefier-catalog) ready and can just completely replace the icon finding logic.

**Comment by ronjouch** [comment] 2021-09-11 19:47
> @ronjouch @TheCleric Since this seems to be a very common issue, we may just want to remove the ing logo from[ nativefier-icons](https://github.com/nativefier/nativefier-icons) until we get [nativefier-catalog](https://github.com/mattruzzi/nativefier-catalog) ready and can just completely replace the icon finding logic. 

True! Good suggestion, thx. Will do.

**Comment by champagnealexandre** [comment] 2021-09-12 00:03
@mattruzzi or simply add an option in the CLI to bypass nativefier-icons lookup? Could be a very simple workaround in the meantime ; automatic fetching of website icons seems to work quite well.

**Comment by ronjouch** [comment] 2021-09-20 16:06
Frequently-colliding ING icon removed in https://github.com/nativefier/nativefier-icons/commit/dd755501cade125e23ed3a3bf00c994f5e3b4748 ; thx for the suggestion @mattruzzi 🙂.

> or simply add an option in the CLI to bypass nativefier-icons lookup? Could be a very simple workaround in the meantime ; automatic fetching of website icons seems to work quite well.

@champagnealexandre Matt's suggestion was the simplest to cover this icon that people are frequently confused about (but common icon inferring otherwise works well). We already have a zillion CLI options, the more we avoid adding, the merrier I am.

With that, closing. Thanks for the report.

**Closed by ronjouch** 2021-09-20 16:06 UTC
Labels: bug

**Comment by champagnealexandre** [comment] 2021-09-21 14:43
no problem @ronjouch, thanks for the great work!

Cheers,
