### ISSUE TITLE
How to enable Screen Sharing for Jitsi Meet embedded videoconference?

### ISSUE THREAD

**Issue by inglesuniversal** [nativefier/nativefier#1280] opened 2021-09-16 14:19 UTC
I can use the mic and even select video sources or share a YouTube video while connected with other users

BUT clicking on Screen Share does not show any prompts to allow it

I even went into my MacOS Big Sur (latest version) privacy settings and allowed screen recording manually, but even after rebooting my Mac nothing happens when clicking on the Screen Share icon within Jitsi Meet embedded js window

Any pointers on how to solve/fix this issue?

Big Time CONGRATULATIONS to all the Nativefier Team and Collaborators

NOTE: I tried the same by creating a test app with Google Meet and there is no way to share screen even if I enable permissions inside the same privacy panel for screen recording :(   I think this is a highly requested feature these days.

**Comment by mattruzzi** [comment] 2021-09-16 18:53
Duplicate of #927?

**Comment by ronjouch** [comment] 2021-09-20 15:57
> Duplicate of #927?

Yup, thanks Matt. Closing; @inglesuniversal pls look at / follow #927

**Closed by ronjouch** 2021-09-20 15:57 UTC
Labels: question
