### ISSUE TITLE
CSS injection doesn't work for elements nested in an iframe

### ISSUE THREAD

**Issue by PetertheRees** [nativefier/nativefier#1325] opened 2021-12-11 15:46 UTC
When building a css injection I cannot target a div that has and id and class. I am only trying to display : none on a panel but I cannot seem to target it. My question is how would I get my css file to work targeting this specific id?

Your question, expressed clearly and concisely.

![image](https://user-images.githubusercontent.com/95971224/145682542-44e74172-14e5-4c39-bbe9-66ff65457e78.png)

What I am using

/* Hide_Dodaac.css */

/* Panel is hidden... */

#ext-comp-1008 div.one-explorer-navigation-panel {
    display: none;
}

built with 
Nativefier 45.0.5

**Comment by ronjouch** [comment] 2021-12-11 15:58
You want to add `!important

> #ext-comp-1008 div.one-explorer-navigation-panel {
> display: none !important;
> }

See [inject docs](https://github.com/nativefier/nativefier/blob/master/API.md#inject):

> _Note about CSS injection:_ to override existing CSS rules, you need to use the `!important` CSS keyword. Example: `#id_to_hide { display: none !important; }` , not just `#id_to_hide { display: none; }` .

**Comment by PetertheRees** [comment] 2021-12-11 16:10
That didn't allow me to inject that change. Do I need to target the id and class?

**Comment by ronjouch** [comment] 2021-12-11 16:12
Ha, ok, re-reading your screenshot & description, found it. 

`#ext-comp-1008 div.one-explorer-navigation-panel` isn't a correct selector. You want `#ext-comp-1008.one-explorer-navigation-panel` or `div#ext-comp-1008.one-explorer-navigation-panel`

**Comment by PetertheRees** [comment] 2021-12-11 16:22
Ill keep trying, for some reason that didn't work for me. Maybe this isn't something I can choose to hide. Thank you for helping.

**Comment by PetertheRees** [comment] 2021-12-11 16:51
I've gotten other injections to work but for some reason targeting this "id" inside and iframe seems to be impossible. 

Css that works for other display : none

/* Hide_Search_bar.css */

/* Bar is hidden... */

.GlobalSidebar__container___v7lZN .GlobalSidebar__button___1-Xik.GlobalSidebar__disabled___1P25F {display: none;!important}

.neo-light .SearchBar__container___3K_-I {display: none; !important}


This is what I have tried with your help but i'm still not able to get this to work.

/* Hide_Dodaac.css */

/* Panel is hidden... */

#ext-comp-1008 {display: none; !important}

div#ext-comp-1008.one-explorer-navigation-panel {display: none; !important}

![image](https://user-images.githubusercontent.com/95971224/145684830-25d0f831-bcab-4023-852d-43135316b48d.png)

**Comment by PetertheRees** [comment] 2021-12-11 19:08
Could it be that this is not the first page that is opened, thats causing this problem?

**Comment by PetertheRees** [comment] 2021-12-12 23:17
Is there a way to load the css once the element is loaded in? or to run it on a loop?

**Comment by TheCleric** [comment] 2021-12-13 14:42
The root issue here is that it's in an iframe which does not follow its parent's css. You'd probably have to write a custom injected js that gets the iframe by id, and then finds the element within that iframe and us JS to edit its CSS from there.

**Comment by ronjouch** [comment] 2022-01-09 14:40
Closing as duplicate of #392.

**Closed by ronjouch** 2022-01-09 14:40 UTC
Labels: question
