### ISSUE TITLE
Application window always contain "nativefier-some-id" in the name even when specifying a custom name

### ISSUE THREAD

**Issue by brpaz** [nativefier/nativefier#851] opened 2019-09-08 21:46 UTC
when generating an application, specifying the `name` argument like:

```
nativefier --name "Some Awesome App" "http://medium.com" 
```

The window name appears like `awesome-app-nativefier-some-random-id`. Is there anyway I can just have the name I specified and not append the nativefier part?

Thank you.

**Comment by mxdpeep** [comment] 2019-09-10 09:05
cannot confirm, shows Some Awesome App and then changes to Medium - ...

**Comment by brpaz** [comment] 2019-09-11 20:57
Sorry, I wasn´t clear enough. I am not talking about the Application title itself, but the name that appears in the window list or the application icon in the dock.

See here: https://imgur.com/a/AMh1Sxg

**Comment by chriscarpenter12** [comment] 2019-09-14 16:01
Can confirm I see the same thing as @brpaz 

![image](https://user-images.githubusercontent.com/458486/64910694-5007f900-d6e7-11e9-9b02-4e6927cc4425.png)

Created with:
```
nativefier \
--name "Outlook" \
--icon ~/Desktop/outlook.png \
--internal-urls ".*(office|office365|sharepoint|microsoft|onenote)\.(com).*" \
--tray \
--counter \
--single-instance \
'https://outlook.office.com'
```

**Comment by ravenyu** [comment] 2019-09-15 04:11
Got the same issue here. 
Really not the most elegant 😕

<img width="356" alt="Screen Shot 2019-09-15 at 12 11 17 PM" src="https://user-images.githubusercontent.com/28529669/64916560-f0c2eb00-d7b1-11e9-86af-3a5ab6d498f9.png">

**Comment by mxdpeep** [comment] 2019-09-17 12:13
not related to Windows then, I cannot confirm on Linux, I am using WSL and headless only

**Comment by m2de** [comment] 2019-12-14 10:16
Has anyone got a solution to this? Same problem on 7.7.0 on Mac OS 10.14.6. The about screen shows `xxxx-nativefier-id` when setting a custom app name or leaving it to default.

**Comment by 0xnu** [comment] 2019-12-26 20:45
Submitted a [PR](https://github.com/jiahaog/nativefier/pull/888) for it. Fingers crossed.

**Comment by voltechs** [comment] 2020-01-06 20:22
@0xnu there are a few failing tests on your [PR](https://github.com/jiahaog/nativefier/pull/888). Probably will need to resolve that before it's a candidate for merging.

**Comment by 0xnu** [comment] 2020-01-11 14:55
> @0xnu there are a few failing tests on your [PR](https://github.com/jiahaog/nativefier/pull/888). Probably will need to resolve that before it's a candidate for merging.

@voltechs All done. Thanks a lot.

**Comment by SiqingYu** [comment] 2020-02-04 17:35
Long-time issue on Linux GNOME desktop environment.
Reproduced on GNOME Shell 3.28.4
<img width="523" alt="2020-02-05_01-33" src="https://user-images.githubusercontent.com/22290018/73770609-a3bed000-47b7-11ea-8de8-d81fdce680be.png">

**Comment by SiqingYu** [comment] 2020-02-04 17:37
@chriscarpenter12's solution works like a charm.

**Comment by iancleary** [comment] 2020-03-21 00:41
Confirmed on Ubuntu-18.04 using Nativefier v8.0.4:
![image](https://user-images.githubusercontent.com/9398410/77215585-07842a80-6ad2-11ea-8a0e-dba5afb665cd.png)


@SiqingYu @chriscarpenter12 Same, the Desktop solution above works like a charm. Thanks :rocket: 

Unrelated to the random ID, but for those looking to use ansible, I made a role to install TickTick with similar settings to the Outlook example above.

Source: https://github.com/iancleary/personal-ansible/tree/v0.6.0/roles/ticktick

**Comment by asdil12** [comment] 2020-04-21 15:07
You can simply update the `name` in the `resources/app/package.json` after nativefying the app as a workaround until the PR gets merged.
```bash
nativefier -n Riot https://riot.im/app/
jq '.name="Riot"' ~/Riot-linux-x64/resources/app/package.json
```

**Comment by iancleary** [comment] 2020-04-21 17:38
@asdil12 Thank you!  Confirming that also allows worked for me. 

That also allows users on `Ubuntu/GNOME` to save the application to their Favorites Bar.

**Comment by prampey** [comment] 2020-05-05 19:04
@chriscarpenter12 's solution not only works but seems like the best way to install and register an application on Linux. It provides a launcher that can be added to the desktop or searchable in the applications menu.
I'd like to work on a PR to provide a command-line option for this behavior.
Any thoughts/suggestions on where I should start looking?

**Comment by SiqingYu** [comment] 2020-12-22 03:26
While @chriscarpenter12 's solution doesn't change the app's name in the GNOME lock screen notification, @asdil12 's solution changes it.

**Comment by TheCleric** [comment] 2021-04-29 19:01
@brpaz @SiqingYu @iancleary wondering if this is till an issue for you in the latest builds. I think the About menu item does not exist anymore, but have not seen any of the other behavior described here.

**Comment by iancleary** [comment] 2021-04-30 03:46
> @brpaz @SiqingYu @iancleary wondering if this is till an issue for you in the latest builds. I think the About menu item does not exist anymore, but have not seen any of the other behavior described here.

Hello @TheCleric, I upgrade nativefier and recreated my process to check.

## Background on version and desktop (in case that is important)
![OS version of my test](https://user-images.githubusercontent.com/9398410/116645257-423dd080-a92a-11eb-9dba-a59da65dfd40.png)

## Recreation
```
> nativefier --version
43.0.2

> nativefier "https://ticktick.com" /tmp/nativefier/ticktick
      --name "TickTick" 
      --internal-urls ".*(ticktick)\.(com).*"
      --tray 
      --single-instance
                  
Cannot automatically retrieve the app icon: Request failed with status code 401

Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
Packaging app for platform linux x64 using electron v12.0.4

Finalizing build...
App built to /home/iancleary/TickTick-linux-x64, move to wherever it makes sense for you and run the contained executable file (prefixing with ./ if necessary)
Menu/desktop shortcuts are up to you, because Nativefier cannot know where you're going to move the app. Search for "linux .desktop file" for help, or see https://wiki.archlinux.org/index.php/Desktop_entries                                                            
```
### Run Exectuable from CLI

If I run the application from the command line

`./TickTick`

then the application name appears to match the nativefier CLI arguement

![icon name when run directly from executable](https://user-images.githubusercontent.com/9398410/116644687-e161c880-a928-11eb-9339-5fe00b89a32b.png)

### Desktop file
```
> cat resources/app/package.json 
{"name":"ticktick-nativefier-7be916","version":"1.0.0","description":"Placeholder for the nativefier cli to override with a target url","main":"lib/main.js","author":"Jia Hao","license":"MIT","keywords":["desktop","electron","placeholder"],"scripts":{},"dependencies":{"electron-context-menu":"^2.5.0","electron-dl":"^3.2.0","electron-squirrel-startup":"^1.0.0","electron-window-state":"^5.0.3","source-map-support":"^0.5.19"},"devDependencies":{"electron":"^12.0.1"}}
```

Then created a desktop entry here: `~/.local/share/applications/ticktick.desktop`, without the `StartupWMClass=ticktick-nativefier-7be916
`
```
[Desktop Entry]
Name=TickTick
Comment=TickTick Web
GenericName=TickTick
Exec=/opt/ticktick/TickTick
Icon=/opt/ticktick/resources/app/icon.png
Type=Application
StartupNotify=true
Categories=Office;
Keywords=ticktick;
```

![image](https://user-images.githubusercontent.com/9398410/116644814-3c93bb00-a929-11eb-9bad-49dee80ebecf.png)


---

Then created a desktop entry here: `~/.local/share/applications/ticktick.desktop`, with the `StartupWMClass=ticktick-nativefier-7be916` line.
```
[Desktop Entry]
Name=TickTick
Comment=TickTick Web
GenericName=TickTick
Exec=/opt/ticktick/TickTick
Icon=/opt/ticktick/resources/app/icon.png
Type=Application
StartupNotify=true
StartupWMClass=ticktick-nativefier-7be916
Categories=Office;
Keywords=ticktick;
```

![image](https://user-images.githubusercontent.com/9398410/116644897-749afe00-a929-11eb-8589-12cf02ea8f04.png)


If you launch the app from the executable directly, the name matches the nativefier command line arguement `--name`.

If the user creates a desktop entry for their user interface (GNOME in my case) and launches the executable from their (at least on GNOME), then the desktop file with the matching `StartupWMClass` is required. Said another way, the nativefier command line arguement doesn't propagate to the name key value pair in the package.json file for me using nativefier `43.0.2`.  

## Takeaway from my recreation

I'm not sure what the community wants to maintain/support in regards to how a user's desktop entry is created (by them or by the nativefier command), but the answer (from my recreation) seems to depend on how the user launches the created app.  I don't know that much about desktops and how they launch applications, but it appears to be different than the CLI.  Some one else may know more. 
I don't know if the behavior is changed since my comment last year.  It appears a customized desktop file is and was required when launching from the Activities view in GNOME.

I'm personally fine with creating a desktop file.

I hope this helps :)

**Comment by TheCleric** [comment] 2021-04-30 05:18
@iancleary that is some great info. Thanks so much! I think since everything but the .desktop file works, and we don't currently support creating a .desktop file, I'm going to say this looks resolved.

If anyone still sees this issue, please comment and we can look at reopening it.

**Closed by TheCleric** 2021-04-30 05:18 UTC
Labels: need-info
