### ISSUE TITLE
[Google Meet, Teams, etc] No sharescreen selection window created at the javascript “navigator.mediaDevices.getDisplayMedia()” command

### ISSUE THREAD

**Issue by stevebbs** [nativefier/nativefier#1180] opened 2021-05-06 08:57 UTC
- [ yes] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [ yes] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [ yes] I searched existing issues, open & closed. Yes, my bug is new.
- [yes ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

Version of Nativefier: 43.1.2
Version of Node.js:  v14.16.1
Command line parameters:   nativefier --name "test" "https://bbsthai.org/test/testsc.htm"
OS and architecture you are running Nativefier from:   Windows10 64bit

**Instructions to reproduce the issue:**
Try https://bbsthai.org/test/testsc.htm in a normal browser (e.g. chrome). Press the “sharecreen” button and a sharescreen selection window opens.
Then try it from the app generated in nativefier. Nothing happens when you press the button.

For simplicity I've reduced the javascript to a single line: 
displayMediaStream = navigator.mediaDevices.getDisplayMedia();

Can anyone help? Is there an browserwindow-options value that needs inserting when generating the app?

**Comment by TheCleric** [comment] 2021-05-07 20:12
Unfortunately Electron (which underlies Nativefier), doesn't support getMediaDisplay. It does however support an internal [`desktopCapturer.getSources`](https://www.electronjs.org/docs/api/desktop-capturer#desktopcapturergetsourcesoptions). You could possibly inject a JS file that polyfills `getMediaDisplay` with `getSources`. Some have indicated some success in doing so (https://github.com/electron/electron/issues/16513#issuecomment-602070250). I've tried replicating some of this functionality within the app, but the polyfill fails to be called with a DOMException for some reason. You can see my attempt here if you're wishing to build upon it:

https://github.com/TheCleric/nativefier/tree/feature/get_display_media

**Comment by TheCleric** [comment] 2021-05-10 13:50
Possible duplicate of #927 or #971

**Comment by ronjouch** [comment] 2021-05-18 03:15
Closing as dup of https://github.com/nativefier/nativefier/issues/927 .

**Closed by ronjouch** 2021-05-18 03:15 UTC
Labels: bug
