### ISSUE TITLE
how do i pack the unpacked application

### ISSUE THREAD

**Issue by atordvairn** [nativefier/nativefier#1358] opened 2022-02-22 12:30 UTC
how do i pack the unpacked application in Linux build ?

when i run the command in Linux i get the unpacked folder with the executable

the executable can't run solo
how do i pack all the files into a `.deb` or `.appimage` file

**Comment by ronjouch** [comment] 2022-02-22 12:40
Closing as duplicate of #512

**Closed by ronjouch** 2022-02-22 12:40 UTC
Labels: question

**Comment by ronjouch** [comment] 2022-02-22 12:41
> how do i pack all the files into a .deb or .appimage file
See #249

> the executable can't run solo
That's not my experience. What do you mean?
