### ISSUE TITLE
wine: could not load kernel32.dll, status c0000135

### ISSUE THREAD

**Issue by belerweb** [nativefier/nativefier#1354] opened 2022-02-09 10:47 UTC
**Homework**

- [*] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [*] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [*] I searched existing issues, open & closed. Yes, my bug is new.
- [*] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

v46.1.0 build window app failed with error: wine: could not load kernel32.dll, status c0000135

**Steps to reproduce**

```
docker run --rm nativefier/nativefier:v46.1.0 -p windows https://www.google.com

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
Packaging app for platform win32 x64 using electron v16.0.8
Error during build. Run with --verbose for details. ExitCodeError: Command failed with a non-zero return code (53):
wine64 /nativefier/node_modules/rcedit/bin/rcedit-x64.exe /nativefier/APP-win32-x64/APP.exe --set-version-string FileDescription  --set-version-string InternalName  --set-version-string OriginalFilename APP.exe --set-version-string ProductName  --set-version-string CompanyName Jia Hao --set-file-version 1.0.0 --set-product-version 1.0.0

wine: could not load kernel32.dll, status c0000135
    at ChildProcess.<anonymous> (/nativefier/node_modules/@malept/cross-spawn-promise/src/index.ts:172:16)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at Pipe.<anonymous> (net.js:675:12) {
  cmd: 'wine64',
  args: [
    '/nativefier/node_modules/rcedit/bin/rcedit-x64.exe',
    '/nativefier/APP-win32-x64/APP.exe',
    '--set-version-string',
    'FileDescription',
    undefined,
    '--set-version-string',
    'InternalName',
    undefined,
    '--set-version-string',
    'OriginalFilename',
    'APP.exe',
    '--set-version-string',
    'ProductName',
    undefined,
    '--set-version-string',
    'CompanyName',
    'Jia Hao',
    '--set-file-version',
    '1.0.0',
    '--set-product-version',
    '1.0.0'
  ],
  stdout: '',
  stderr: 'wine: could not load kernel32.dll, status c0000135\n',
  code: 53
}
```

**Expected behavior**

What you expected to happen.

**Actual behavior**

wine: could not load kernel32.dll, status c0000135

**Debug info**

**Context**

 - Nativefier: v46.1.0

**Comment by ronjouch** [comment] 2022-02-10 03:11
Cannot reproduce the issue here on Nativefier 46.1.0 and Wine 7.1 on Arch. With that, closing. Please dig around your wine installation. Will re-open if you manage to provide a broken scenario with the latest Wine.

**Closed by ronjouch** 2022-02-10 03:11 UTC
Labels: bug
