### ISSUE TITLE
Support opening URLs passed as parameter to Nativefied application (+ "deep linking")

### ISSUE THREAD

**Issue by dsemaya** [nativefier/nativefier#405] opened 2017-07-10 21:47 UTC
### Description
It doesn't seem to be possible to have a Nativefier app open up links from other apps.  This works with Epichrome, but Nativefier apps are much nicer to use.  

### Steps to Reproduce Issue
Try to drag URL to dock icon of Nativefier app - nothing happens. 
Use Choosy to set up custom rule to open Nativefier app as browser for certain links - app comes to foreground but doesn't open link.  

### Specifications
Version of Nativefier 7.4.0
Version of Node.jsv6.9.1
OS: macOS 10.12.5
Architecture: x86

**Comment by ronjouch** [comment] 2017-07-13 14:09
Hi @dsemaya, thanks for the feedback 👍. Not sure I want to file this as feature request though, such a feature would be precisely opposed to Nativefier's main goal, which is precisely to bundle applications. If you have to open an URL, well, use your browser 🙂. Want it to be isolated? Well, open it in an incognito window.

Closing, but I may be missing something; feel free to argue and we can re-open.

**Comment by dsemaya** [comment] 2017-07-13 17:45
Reopening this.

The use case is Google Docs.  Each document is a unique URL.  I want to create a Docs app, a Slides app, and a Sheets app.  I want to edit documents in windows, each within their own app, like a native office suite (Office/iWork).  In order to do this I need my Nativefier apps to receive URLs.  

If someone sends me a link to a doc in Gmail, I want my Gmail Nativefier app to open the document in my Docs app, not a browser tab.  There's no way to do that if the Docs app can't receive URLs.

This use case is very similar to iOS.  There are native apps for Google Docs, Sheets, and Slides. When you tap on a link to a doc the OS intelligently opens the Docs app, not a web page in Safari.  I want to create the same thing. 

If Nativefier could just receive HTTPS URLs to start with, [Choosy](http://choosyosx.com) or [Browser Fairy](http://www.browserfairy.com) can handle which app should launch for each URL domain.  Long term it would be great if apps could register their own URL helper scheme.

From an outsider's perspective this initial functionality doesn't seem particularly difficult.  Just open whatever HTTP URL is passed through, as long as it matches the internal-urls regex.  It's very similar to Gmail spawning secondary windows except the URLs are coming from outside the app, not inside.  

It also seems to fit perfectly within Nativefier's goal of taking popular web apps and making them feel native. That's exactly what I'm trying to do.

Therefore, in response:
> You have to open a one-time URL?
> → Use your browser 🙂.

Each Doc has a unique URL.  I open countless unique Docs URLs daily.


> It's a one-time URL but you want it to be isolated?
> → Open it in an incognito window in your browser.

I don't want to edit Docs in a browser tab, I want to edit them in my Docs app.  The Docs app is a superior experience since it feels like a native word processor.  The windows are cleaner and each document has its own window.


> It's not a one-time URL but a frequently-used app?
> → Well, nativefy it.

It is a very frequently used app, but I need it to open the proper URL for each document link when I click on it in other apps.

**Comment by ronjouch** [comment] 2017-07-13 18:11
@dsemaya thanks for the clarification 👍. Makes sense, now that I know your use case is opening URLs *"for the same app"*. Your first-time description sounded like dragging youtube.com on a facebook app, which made no sense.

Re-opening (which only means the issue is open, no guarantee anyone will work on that).

**Comment by davidolrik** [comment] 2017-09-28 14:56
I have the same issue - I have created a "Jira" app and want urls to specific issues to open in my "Jira" app.

**Comment by ronjouch** [comment] 2018-05-12 16:33
This issue was mixing two concerns; claryfing them based on feedback from @jancbeck on #604. The two concerns are:

1. Dispatch opening URLs to different browser/apps depending on the URL (matching the domain or a regex/wildcard pattern).
    - Linux: I do it with a [custom xdg-open script](https://superuser.com/questions/688063/is-there-a-way-to-redirect-certain-urls-to-specific-web-browsers-in-linux).
    - macOS: use [Choosy](https://www.choosyosx.com/).
    - Windows: I don't know, feedback welcome.
2. Let Nativefied apps accept and open a site passed as parameter. *This* is what this issud is about and I renamed the issue to make that clear. PR still welcome 🙂.

**Comment by jancbeck** [comment] 2018-06-03 11:13
Looks like the "open-url" event could be helpful:

```
app.on('open-url', function(event, url) {
  console.log("Open URL: " + url);
  event.preventDefault();
});
```
Tried adding that to main.js and manually editing Info.plist to support http(s) but I'm not getting anything back in the console. 
Also it is a [macOS-only](https://stackoverflow.com/questions/38458857/electron-url-scheme-open-url-event) feature, but I'm testing on macOS.

**Comment by ELLIOTTCABLE** [comment] 2018-09-10 20:31
I installed Choosy, but I don't see how that helps:

 - I Nativefied <https://app.asana.com>,
 - then configured Choosy to map `app.asana.com` to Asana.app:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/200/45322669-8fb56700-b50e-11e8-8dae-7ddb28b602bd.png">

Now, while that app activates (or launches) when I click an Asana link, it doesn't actually *navigate* there. What do I do?

**Comment by jancbeck** [comment] 2018-09-11 10:45
@ELLIOTTCABLE you reproduced what this issue is about. You could submit a PR or just hope somebody else pics it up.

**Comment by dahjelle** [comment] 2019-03-14 19:37
For macOS, does Electron's ['open-url' event](https://electronjs.org/docs/api/app#event-open-url-macos) do this behavior?

**Comment by Fanman03** [comment] 2019-09-10 03:48
@ronjouch I found what appears to be a Choosey equivalent for Windows, [`BrowserSelector`](https://github.com/DanTup/BrowserSelector) . Any progress on getting Nativefier to support the core of this issue?

**Comment by Fmstrat** [comment] 2021-04-20 21:18
I'm building an Office 365 application that syncs a local file to OneDrive, opens the Web Editor via nativefier, then resyncs the file when complete. I needed this ability to incorporate opening files directly from the file manager. I'm worried the above PR is missing something since it was so easy to add and then has been open for so long. But hey, I guess it's all about getting eyes on something.

```
# Opens the default URL:
myapp

# Opens a custom URL:
myapp "https://my.site.com"
```

Once my app is done I will provide a direct-code link so people can see how I'm using the PR if that helps, but it's pretty self explanatory.

**Comment by Fmstrat** [comment] 2021-04-21 22:52
Here's it in active use: https://github.com/Fmstrat/loffice-365

**Closed** 2021-04-29 00:18 UTC
Labels: feature-request

**Comment by mizzunet** [comment] 2021-11-06 04:32
So, could anyone tell me how can I make 'mailto://' to redirect to nativified ProtonMail?
I have set `x-scheme-handler/mailto=ProtonMail.desktop`, so `xdg-open` open the the program but error occurs
```
xdg-open mailto://
onReady ERROR Error: ERR_FAILED (-2) loading 'mailto://'
    at rejectAndCleanup (electron/js2c/browser_init.js:213:985)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:213:1360)
    at Object.emit (events.js:315:20) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'mailto://'
}
```

**Comment by axsuul** [comment] 2021-11-07 16:37
Has anyone gotten this to work with Finicky yet?

**Comment by Kinark** [comment] 2022-03-25 17:01
Why the heck is this closed? It's still not possible to open mailto links in nativefier!

**Comment by ronjouch** [comment] 2022-03-27 13:48
> Why the heck is this closed? It's still not possible to open mailto links in nativefier!

@Kinark please

1. Open a separate mailto issue.
2. Don't be a dick.

**Comment by NeighNeighNeigh** [comment] 2023-09-12 05:29
Hey guys, I understand this is now implemented, but would someone explain how to make use of it?
Here is what I am hoping to achieve:
 - Nativefier app will default open to (for example) animals.com on launch.
 - _Unless_ I specified an alternative URL when launching via terminal, such as animals.com/tutles
 - While open, I can also issue a terminal command to the Nativefier app to go to a new url, like animals.com/foxes
 If anyone could help me understand how this is done, it would be awesome
