### ISSUE TITLE
cursor align with text   !!!

### ISSUE THREAD

**Issue by Kun1605** [nativefier/nativefier#1458] opened 2022-08-28 05:53 UTC
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my bug is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Nativefier command

nativefier -p linux -a x64 -n  Kibana --tray --single-instance  --ignore-certificate   --icon=/home/yk/图片/apps/kibana.png https://node01:5601/app/dev_tools

### Steps to reproduce

build with nativefier 

### Expected behavior

cursor align with text  like this , for example i use firefox
![image](https://user-images.githubusercontent.com/19654613/187059758-ec7588d0-83f4-4e09-a81e-3211a5e60d0c.png)

### Actual behavior

cursor does not align with text like this 
![image](https://user-images.githubusercontent.com/19654613/187059709-0c89645e-5d68-4db8-bbda-e2c9b6184865.png)

### Debug info

none

### Nativefier version

49.0.0

### Node.js version

v14.20.0

### npm version

6.14.17

### OS

ubuntu18.04

**Comment by BastelPichi** [comment] 2022-08-29 17:53
Are you sure this works in chrome?

**Comment by ronjouch** [comment] 2022-09-11 04:14
> Are you sure this works in chrome?

@BastelPichi yeah, I too suspect it doesn't. With that, closing. Happy to re-open if you confirm the problem is Nativefier-specific and doesn't happen in Chrome. If it does, please provide a repro scenario on a ***public*** website.

**Closed by ronjouch** 2022-09-11 04:14 UTC
Labels: bug
