### ISSUE TITLE
--injecting multiple js files mangles them in nativefied app

### ISSUE THREAD

**Issue by jplot** [nativefier/nativefier#458] opened 2017-10-03 13:50 UTC
## Description

When injecting multiple files, the final rendering of the inject.js file is corrupted

#### test1.js
```javascript
alert('Test1')
```

#### test2.js
```javascript
console.log('Test2')
```

#### Run
```shell
nativefier --inject test1.js --inject test2.js --name Github https://github.com
```

####  Github.app/Contents/Resources/app/inject/inject.js
```javascript
alert('Test1')
st2')
```

## Specifications

Version of Nativefier (run `nativefier --version`): `v7.4.1`
Version of Node.js (run `node --version`): `v8.5.0`
OS: `macOS High Sierra 10.13.1`

**Comment by ronjouch** [comment] 2017-10-03 15:38
@jplot merci du retour 👍. Before I give a try at reproducing the issue, one wording nit: when you say *"deteriorated"*, are you saying Nativefier regressed? (Said differently, did it use to work? If yes, when and any idea when it started mangling data?) Thanks.

**Comment by jplot** [comment] 2017-10-04 10:12
@ronjouch No it does not work, from the second file inject it corrupts inject.js

**Comment by ronjouch** [comment] 2017-10-04 11:34
> *No it does not work, from the second file inject it corrupts inject.js*

@jplot I get that, but my question is: has it already worked in an earlier version of Nativefier?

**Comment by jplot** [comment] 2017-10-04 12:51
@ronjouch  Yes, 7.4.0 and 7.4.1

**Comment by ronjouch** [comment] 2017-10-04 13:07
Still not clear, please make a complete sentence.

**Comment by jplot** [comment] 2017-10-04 13:48
does not work on Nativefier v7.4.0 and v7.4.1

**Comment by zbirkenbuel** [comment] 2018-01-24 21:39
I believe the problem as reported is that the user is trying to inject two script files and that just isn't supported.  The `--inject` handler in the [build script](https://github.com/jiahaog/nativefier/blob/master/src/build/buildApp.js#L63-L86) copies any injected js file to `inject.js` without any consideration for multiple files.  

As to why it's got the strange content rather than just being one file or the other, under the covers it looks like the injection handling functions uses the [ncp](https://github.com/jiahaog/nativefier/blob/master/src/build/buildApp.js#L5-L7) library to perform file copies and  _that_ library uses [stream copying](https://github.com/AvianFlu/ncp/blob/master/lib/ncp.js#L113-L135), so it's probably overwriting only portions of the file.

Scenario, those two files end with newline characters (`\n`), it first copies characters 1-21 of the string `console.log('Test2')\n` and then overwrites characters 1-15 of that with `alert('Test1')\n` giving you `alert('Test1')\nst2')`

**Comment by Aidoboy** [comment] 2018-06-18 06:27
It looks like the behavior now is that one js file is randomly picked. It would be nice to be able to pick.

**Comment by xeor** [comment] 2020-09-09 09:34
It seams like this is still an issue. For me, the last `--inject ....js` wins, and the first one is ignored.

**Comment by vviikk** [comment] 2021-02-21 17:19
I can fix this in the next PR as I'll be making one about injection. I already have a solution.

**Comment by mattruzzi** [comment] 2021-04-19 02:21
@vviikk Can you split the fix for this into a separate pr so it can be merged sooner without the gist url injection part having to be completed?

**Closed** 2021-04-30 15:04 UTC
Labels: bug
