### ISSUE TITLE
Can't get nativefier to work on debian for home assistant

### ISSUE THREAD

**Issue by Buster14** [nativefier/nativefier#1460] opened 2022-09-11 03:00 UTC
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my bug is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Nativefier command

nativefier --name "Home_Assistant" 'http://192.168.100.21:8123'

### Steps to reproduce

I installed nativiefier on snap debian,
run the command above.

### Expected behavior

Home asssitant page opens and login webpage displayed

### Actual behavior

App home assistant open but it's blank

### Debug info

```
App built to /home/gowongan/Home_Assistant-linux-x64/Home_Assistant-linux-x64, move to wherever it makes sense for you and run the contained executable file (prefixing with ./ if necessary)
Menu/desktop shortcuts are up to you, because Nativefier cannot know where you're going to move the app. Search for "linux .desktop file" for help, or see https://wiki.archlinux.org/index.php/Desktop_entries
root@debian:/home/gowongan/Home_Assistant-linux-x64# ./Home_Assistant --no-sandbox
[49631:0911/094714.051277:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[49631:0911/094714.051408:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[49657:0911/094714.097368:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[49657:0911/094714.097602:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[49657:0911/094714.097707:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
No protocol specified
[49657:0911/094714.097957:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[49657:0911/094714.098087:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[49657:0911/094714.098230:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[49657:0911/094714.098361:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[49631:0911/094714.101278:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[49657:0911/094714.105827:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[49631:0911/094714.135485:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[49668:0911/094714.219984:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[49668:0911/094714.220202:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[49668:0911/094714.220372:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
No protocol specified
[49668:0911/094714.220841:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[49668:0911/094714.221004:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[49668:0911/094714.221165:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[49668:0911/094714.221292:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[49668:0911/094714.228382:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[49682:0911/094714.285503:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[49682:0911/094714.285983:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[49682:0911/094714.286462:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Not initialized.
[49682:0911/094714.288211:ERROR:gl_surface_egl.cc(1489)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[49682:0911/094714.288382:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[49682:0911/094714.308375:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
No protocol specified
No protocol specified
[49700:0911/094714.350854:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is 
[49700:0911/094714.378460:ERROR:x11_software_bitmap_presenter.cc(141)] XGetWindowAttributes failed for window 73400323
onReady ERROR Error: ERR_ABORTED (-3) loading 'http://192.168.100.21:8123/auth/authorize?response_type=code&redirect_uri=http%3A%2F%2F192.168.100.21%3A8123%2F%3Fauth_callback%3D1&client_id=http%3A%2F%2F192.168.100.21%3A8123%2F&state=eyJoYXNzVXJsIjoiaHR0cDovLzE5Mi4xNjguMTAwLjIxOjgxMjMiLCJjbGllbnRJZCI6Imh0dHA6Ly8xOTIuMTY4LjEwMC4yMTo4MTIzLyJ9'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.navigationListener (node:electron/js2c/browser_init:161:7953)
    at EventEmitter.emit (node:events:526:28) {
  errno: -3,
  code: 'ERR_ABORTED',
  url: 'http://192.168.100.21:8123/auth/authorize?response_type=code&redirect_uri=http%3A%2F%2F192.168.100.21%3A8123%2F%3Fauth_callback%3D1&client_id=http%3A%2F%2F192.168.100.21%3A8123%2F&state=eyJoYXNzVXJsIjoiaHR0cDovLzE5Mi4xNjguMTAwLjIxOjgxMjMiLCJjbGllbnRJZCI6Imh0dHA6Ly8xOTIuMTY4LjEwMC4yMTo4MTIzLyJ9'
}

```

### Nativefier version

49.01

### Node.js version

22.12.22

### npm version

22.12.22

### OS

debian 11 bullseye

**Comment by ronjouch** [comment] 2022-09-11 03:08
@Buster14 please provide a scenario reproducible on a ***public*** site, as requested by the issue template. With that, closing, will re-open if you provide a public repro.

That being said, looking at all the errors, it looks like your display server / GPU / driver is misconfigured. Can you run Chromium? Did you try our flag `--disable-gpu` ?

![screenshot_public-please_2022-09-10-23:02:34](https://user-images.githubusercontent.com/522085/189510582-07404b8c-8a8a-4365-a73f-e32307bc213e.png)

**Closed by ronjouch** 2022-09-11 03:08 UTC
Labels: bug

**Comment by Buster14** [comment] 2022-09-11 03:19
Thanks for the reply, 
I need it to display lovelace for local home assistant webserver, 
on windows it was lighter compared to running full blown browser, so I give it a shot on debian.
Forgot to mention the webpage has 2 webrtc streams if that matters, but it only shows after logged in.

I just Tried it again with --disablegpu, but it still display a blank webpage

```
root@debian:/home/gowongan# nativefier -m,--disablegpu --name "Home_Assistant" 'http://192.168.100.21:8123'


    Hi! Nativefier is minimally maintained these days, and needs more hands.
    If you have the time & motivation, help with bugfixes and maintenance is VERY welcome.
    Please go to https://github.com/nativefier/nativefier and help how you can. Thanks.



Processing options...

Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...

Finalizing build...
App built to /home/gowongan/Home_Assistant-linux-x64, move to wherever it makes sense for you and run the contained executable file (prefixing with ./ if necessary)
Menu/desktop shortcuts are up to you, because Nativefier cannot know where you're going to move the app. Search for "linux .desktop file" for help, or see https://wiki.archlinux.org/index.php/Desktop_entries
root@debian:/home/gowongan# cd Home_Assistant-linux-x64/
root@debian:/home/gowongan/Home_Assistant-linux-x64# ./Home_Assistant --no-sandbox
[50263:0911/101536.536555:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[50263:0911/101536.536669:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[50289:0911/101536.561216:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[50289:0911/101536.561455:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[50289:0911/101536.561609:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
No protocol specified
[50289:0911/101536.562098:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[50289:0911/101536.562238:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[50289:0911/101536.562362:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[50289:0911/101536.563186:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[50263:0911/101536.582875:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[50289:0911/101536.585083:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[50263:0911/101536.618568:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[50300:0911/101536.693109:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[50300:0911/101536.693286:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[50300:0911/101536.693365:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
No protocol specified
[50300:0911/101536.693634:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[50300:0911/101536.693716:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[50300:0911/101536.693788:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[50300:0911/101536.693860:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[50300:0911/101536.699254:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[50314:0911/101536.736218:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[50314:0911/101536.740652:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[50314:0911/101536.740875:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Not initialized.
[50314:0911/101536.741010:ERROR:gl_surface_egl.cc(1489)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[50314:0911/101536.741166:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[50314:0911/101536.755701:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
No protocol specified
No protocol specified
[50333:0911/101536.841356:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is 
[50333:0911/101536.874187:ERROR:x11_software_bitmap_presenter.cc(141)] XGetWindowAttributes failed for window 73400323
onReady ERROR Error: ERR_ABORTED (-3) loading 'http://192.168.100.21:8123/auth/authorize?response_type=code&redirect_uri=http%3A%2F%2F192.168.100.21%3A8123%2F%3Fauth_callback%3D1&client_id=http%3A%2F%2F192.168.100.21%3A8123%2F&state=eyJoYXNzVXJsIjoiaHR0cDovLzE5Mi4xNjguMTAwLjIxOjgxMjMiLCJjbGllbnRJZCI6Imh0dHA6Ly8xOTIuMTY4LjEwMC4yMTo4MTIzLyJ9'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.navigationListener (node:electron/js2c/browser_init:161:7953)
    at EventEmitter.emit (node:events:526:28) {
  errno: -3,
  code: 'ERR_ABORTED',
  url: 'http://192.168.100.21:8123/auth/authorize?response_type=code&redirect_uri=http%3A%2F%2F192.168.100.21%3A8123%2F%3Fauth_callback%3D1&client_id=http%3A%2F%2F192.168.100.21%3A8123%2F&state=eyJoYXNzVXJsIjoiaHR0cDovLzE5Mi4xNjguMTAwLjIxOjgxMjMiLCJjbGllbnRJZCI6Imh0dHA6Ly8xOTIuMTY4LjEwMC4yMTo4MTIzLyJ9'
```

**Comment by Buster14** [comment] 2022-09-11 03:32
Sorry should've been --disable-gpu. Tried it again but it's still the same though

```
root@debian:/home/gowongan# rm -r Home_Assistant-linux-x64/
root@debian:/home/gowongan# nativefier -m,--disable-gpu --name "Home_Assistant" 'http://192.168.100.21:8123'


    Hi! Nativefier is minimally maintained these days, and needs more hands.
    If you have the time & motivation, help with bugfixes and maintenance is VERY welcome.
    Please go to https://github.com/nativefier/nativefier and help how you can. Thanks.



Processing options...
Cannot automatically retrieve the app icon: connect ETIMEDOUT 185.199.108.153:443 on https://nativefier.github.io/nativefier-icons/

Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...

Finalizing build...
App built to /home/gowongan/Home_Assistant-linux-x64, move to wherever it makes sense for you and run the contained executable file (prefixing with ./ if necessary)
Menu/desktop shortcuts are up to you, because Nativefier cannot know where you're going to move the app. Search for "linux .desktop file" for help, or see https://wiki.archlinux.org/index.php/Desktop_entries
root@debian:/home/gowongan# cd Home_Assistant-linux-x64/
root@debian:/home/gowongan/Home_Assistant-linux-x64# ./Home_Assistant --no-sandbox
[50602:0911/103001.178172:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[50602:0911/103001.178282:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[50629:0911/103001.220609:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[50629:0911/103001.220794:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[50629:0911/103001.221476:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
No protocol specified
[50629:0911/103001.221860:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[50629:0911/103001.221965:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[50629:0911/103001.222047:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[50629:0911/103001.222124:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[50602:0911/103001.227782:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[50629:0911/103001.228162:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[50602:0911/103001.257329:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[50641:0911/103001.324785:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[50641:0911/103001.324977:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[50641:0911/103001.325040:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
No protocol specified
[50641:0911/103001.325475:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[50641:0911/103001.325576:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[50641:0911/103001.325638:ERROR:gl_surface_egl.cc(1489)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[50641:0911/103001.325727:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[50641:0911/103001.340123:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[50655:0911/103001.419587:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[50655:0911/103001.420005:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[50655:0911/103001.420113:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Not initialized.
[50655:0911/103001.420184:ERROR:gl_surface_egl.cc(1489)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[50655:0911/103001.420263:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[50655:0911/103001.427390:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
No protocol specified
No protocol specified
[50674:0911/103001.496659:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is 
[50674:0911/103001.514901:ERROR:x11_software_bitmap_presenter.cc(141)] XGetWindowAttributes failed for window 73400323
onReady ERROR Error: ERR_ABORTED (-3) loading 'http://192.168.100.21:8123/auth/authorize?response_type=code&redirect_uri=http%3A%2F%2F192.168.100.21%3A8123%2F%3Fauth_callback%3D1&client_id=http%3A%2F%2F192.168.100.21%3A8123%2F&state=eyJoYXNzVXJsIjoiaHR0cDovLzE5Mi4xNjguMTAwLjIxOjgxMjMiLCJjbGllbnRJZCI6Imh0dHA6Ly8xOTIuMTY4LjEwMC4yMTo4MTIzLyJ9'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.navigationListener (node:electron/js2c/browser_init:161:7953)
    at EventEmitter.emit (node:events:526:28) {
  errno: -3,
  code: 'ERR_ABORTED',
  url: 'http://192.168.100.21:8123/auth/authorize?response_type=code&redirect_uri=http%3A%2F%2F192.168.100.21%3A8123%2F%3Fauth_callback%3D1&client_id=http%3A%2F%2F192.168.100.21%3A8123%2F&state=eyJoYXNzVXJsIjoiaHR0cDovLzE5Mi4xNjguMTAwLjIxOjgxMjMiLCJjbGllbnRJZCI6Imh0dHA6Ly8xOTIuMTY4LjEwMC4yMTo4MTIzLyJ9'

```

**Comment by ronjouch** [comment] 2022-09-11 04:10
1. `nativefier -m --disable-gpu`, not `nativefier -m,--disable-gpu` 🙂
2. Does it error similarly on a ***public*** website?

**Comment by Buster14** [comment] 2022-09-11 08:28
Sorry just got back,
You're right even with youtube it wont launch.
```
root@debian:/home/gowongan# nativefier -m --disable-gpu --name "youtube" 'www.youtube.com'


    Hi! Nativefier is minimally maintained these days, and needs more hands.
    If you have the time & motivation, help with bugfixes and maintenance is VERY welcome.
    Please go to https://github.com/nativefier/nativefier and help how you can. Thanks.



Processing options...
URL "www.youtube.com" lacks a protocol. Will try to parse it as HTTPS: "https://www.youtube.com". Please pass "http://www.youtube.com" if this is what you meant.
Cannot automatically retrieve the app icon: connect ETIMEDOUT 185.199.108.153:443 on https://nativefier.github.io/nativefier-icons/files/youtube.png

Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...

Finalizing build...
App built to /home/gowongan/youtube-linux-x64, move to wherever it makes sense for you and run the contained executable file (prefixing with ./ if necessary)
Menu/desktop shortcuts are up to you, because Nativefier cannot know where you're going to move the app. Search for "linux .desktop file" for help, or see https://wiki.archlinux.org/index.php/Desktop_entries
root@debian:/home/gowongan# cd youtube
bash: cd: youtube: No such file or directory
root@debian:/home/gowongan# ls
Desktop    Downloads  Pictures	skypeforlinux-64.deb  tl-4.14.0-server	    Videos
Documents  Music      Public	Templates	      tl-4.14.0-server.zip  youtube-linux-x64
root@debian:/home/gowongan# cd youtube-linux-x64/
root@debian:/home/gowongan/youtube-linux-x64# ./youtube 
[0911/152553.717171:FATAL:electron_main_delegate.cc(292)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap
root@debian:/home/gowongan/youtube-linux-x64# ./youtube --no-sandbox
[52588:0911/152559.598478:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[52588:0911/152559.598590:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
No protocol specified
No protocol specified
No protocol specified
[52588:0911/152559.644201:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
No protocol specified
No protocol specified
[52616:0911/152559.656764:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[52616:0911/152559.667776:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[52616:0911/152559.668446:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Not initialized.
[52616:0911/152559.669976:ERROR:gl_surface_egl.cc(1489)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[52616:0911/152559.670320:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[52616:0911/152559.675065:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[52588:0911/152559.683287:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[52632:0911/152559.789851:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[52632:0911/152559.790098:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[52632:0911/152559.790228:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Not initialized.
[52632:0911/152559.790289:ERROR:gl_surface_egl.cc(1489)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[52632:0911/152559.790393:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[52632:0911/152559.811264:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
No protocol specified
No protocol specified
[52648:0911/152559.852011:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is 
[52648:0911/152559.863402:ERROR:x11_software_bitmap_presenter.cc(141)] XGetWindowAttributes failed for window 77594627
[52588:0911/152610.689280:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[52588:0911/152610.689679:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[52588:0911/152610.689743:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```


Is it because I installed it with snap?

**Comment by Buster14** [comment] 2022-09-11 09:06
Ok i reinstalled it with the recommended method (npm ) after removing old installation, but it throws the same error and blank webpage..
I forgot to mention one more thing, I'm running everything via anydesk... does that affect it somehow?

**Comment by ronjouch** [comment] 2022-09-11 13:02
> You're right even with youtube it wont launch.

👍, renamed the issue.

> Is it because I installed it with snap? [...] Ok i reinstalled it with the recommended method (npm) after removing old installation, but it throws the same error and blank webpage..

👍

> I forgot to mention one more thing, I'm running everything via anydesk... does that affect it somehow?

Might be. Looking at the GL/GPU errors, maybe this remote control software means it's an unusual display context, yeah. Try running in a normal non-Anydesk context and tell us.

**Comment by ronjouch** [comment] 2022-09-11 13:50
Hey, I also see you're running as root. Why? That might be the culprit. Try running as non-root and without `--no-sandbox`

**Comment by Buster14** [comment] 2022-09-11 23:17
That did the trick, thanks alot!
btw any other possible way to reduce cpu usage for the created page?
Need to run this as lean as possible since I'm running it with HA server

**Comment by ronjouch** [comment] 2022-09-11 23:28
> That did the trick, thanks alot!

@Buster14 thanks for confirming. I renamed the issue, and I'll add a little guard against that. It's anyway not good security-wise to run apps as root, and it's *particularly* un-good to run a *browser* as root.

Tangentially: if you're new to Linux, do know that root should only be used for exceptional, temporary, ad-hoc maintenance tasks (e.g. editing a config file for 5min), but everyday apps should *absolutely not* be run as root. That's a recipe for behavior & security disaster. It's also different from invoking "Run as Administrator" under Windows, which is sometimes a necessity. Under Linux, that's virtually never the case. If you end up running an app as root, certainly you have a reason, but also certainly you're doing it wrong and you should address the root cause for *having to* run as root. You should never run apps as root. And for the exceptional cases, you should not `su`, you should `sudo mycommand`, to be sure to drop the privileges when done with `command`.

> btw any other possible way to reduce cpu usage for the created page? Need to run this as lean as possible since I'm running it with HA server

Not really. Nativefier apps are Electron apps, a.k.a. Chrome, which certainly eats RAM & CPU. 🤷‍♂️.

**Comment by Buster14** [comment] 2022-09-12 03:45
Thanks for the advice, It's for home use and it's offline so it's relatively safe I think..
Btw sorry if it's slightly out of topic, but are you aware if there is there any other lighter kiosk like app that supports webrtc for HA display? 
I'm running it on N4020 so need it to be as light as possible

**Comment by ronjouch** [comment] 2022-09-12 13:01
> is there any other lighter kiosk like app that supports webrtc for HA display?

@Buster14 for my own kiosk/dashboard needs at work, I just run Chromium on a Raspberry Pi with Chromium's `--kiosk` mode, plus some configuration. I wrote https://unito.io/blog/better-raspberry-pi-dashboards/ to describe what I do to harden stability and self-recovery.

**Comment by Buster14** [comment] 2022-09-12 23:47
Thanks, so a full blown chromium is supposed to be lighter than nativefier's single webpage?
Hmm I'll try comparing the cpu for both but last time i check on windows chromium was too heavy
