### ISSUE TITLE
Nativefier uses incorrect icon for sites that are not in nativefier-icons but contain the name of a site that is

### ISSUE THREAD

**Issue by mattruzzi** [nativefier/nativefier#1125] opened 2021-03-04 03:50 UTC
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [ ] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

Nativefier uses incorrect icon for sites that are not in nativefier-icons but contain the name of a site that is.
Eg. "Duol**ing**o.com", "b**ing**.com" uses ["ing" icon](https://github.com/nativefier/nativefier-icons/blob/gh-pages/files/ing.png) in nativefier-icons from https://www.ing.com.au/

**Steps to reproduce**

Give your ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:

```
$ nativefier https://www.duolingo.com/ --verbose
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

Performing async options post-processing.
Inferring user agent for electron 11.3.0 / darwin
Grabbing electron<->chrome versions file from https://atom.io/download/atom-shell/index.json
Inferring icon for https://www.duolingo.com/ on darwin
Inferring icon from store for https://www.duolingo.com/ on darwin
Allowed icon formats when building for darwin: [ '.icns', '.png', '.ico' ]
Inferring name for https://www.duolingo.com/
Got 249 icons from gitcloud
Max icon match score: 1
Downloading https://nativefier.github.io/nativefier-icons/files/ing.png
Fetched 17.1 kb page at https://www.duolingo.com/
Inferred title: Duolingo
Sanitized filename for Duolingo : Duolingo
Got an icon from the page.
Writing 55.5 kb icon to /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-iconinfer--21341-sJiAIBE156oM/icon.png
Associated electron v11.3.0 to chrome v87.0.4280.141
Given chrome 87.0.4280.141 on darwin, using user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

Preparing Electron app...
Copying electron app from /Users/USER/.n/lib/node_modules/nativefier/app to /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-app--21341-yM1zIfqZOj2K
Writing app config to /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-app--21341-yM1zIfqZOj2K/nativefier.json
No files to inject, skipping copy.
Updating /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-app--21341-yM1zIfqZOj2K/package.json 'name' field to duolingo-nativefier-c2281d

Converting icons...
Converting icon /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-iconinfer--21341-sJiAIBE156oM/icon.png to /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-iconconv--21341-1NKN4EMUanch/icon.icns. Calling shell command: "/Users/USER/.n/lib/node_modules/nativefier/icon-scripts/convertToIcns" "/var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-iconinfer--21341-sJiAIBE156oM/icon.png" "/var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-iconconv--21341-1NKN4EMUanch/icon.icns"
Conversion succeeded and produced icon at /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-iconconv--21341-1NKN4EMUanch/icon.icns
Copying icons if necessary
No copying necessary on macOS; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.2.0
  electron-packager Node v15.10.0
  electron-packager Host Operating system: darwin 17.7.0 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-app--21341-yM1zIfqZOj2K","electronVersion":"11.3.0","icon":"/var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-iconconv--21341-1NKN4EMUanch/icon.icns","name":"Duolingo","out":"/Users/USER","overwrite":true,"platform":"darwin","targetUrl":"https://www.duolingo.com/","tmpdir":false,"win32metadata":{}} +1ms
  electron-packager Target Platforms: darwin +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-app--21341-yM1zIfqZOj2K/package.json +0ms
  electron-packager Application name: Duolingo +10ms
  electron-packager Target Electron version: 11.3.0 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$'
] +0ms
  electron-packager Downloading Electron with options {"platform":"darwin","arch":"x64","version":"11.3.0","artifactName":"electron"} +0ms
Packaging app for platform darwin x64 using electron v11.3.0
  electron-packager Creating /Users/USER/darwin-x64-template +6ms
  electron-packager Extracting /Users/USER/Library/Caches/electron/ad7d1b1b49693bf7121ef728679aa91bceed390f6a4afb9f94f1cff5be54639b/electron-v11.3.0-darwin-x64.zip to /Users/USER/darwin-x64-template +2ms
  electron-packager Initializing app in /Users/USER/Duolingo-darwin-x64 from /Users/USER/darwin-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [
  '/Users/USER/Duolingo-darwin-x64',
  '/Users/USER/Duolingo-darwin-arm64',
  '/Users/USER/Duolingo-linux-ia32',
  '/Users/USER/Duolingo-linux-x64',
  '/Users/USER/Duolingo-linux-armv7l',
  '/Users/USER/Duolingo-linux-arm64',
  '/Users/USER/Duolingo-linux-mips64el',
  '/Users/USER/Duolingo-mas-x64',
  '/Users/USER/Duolingo-mas-arm64',
  '/Users/USER/Duolingo-win32-ia32',
  '/Users/USER/Duolingo-win32-x64',
  '/Users/USER/Duolingo-win32-arm64'
] +4s
  electron-packager Copying icon "/var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-19-24-30-iconconv--21341-1NKN4EMUanch/icon.icns" to app's Resources as "electron.icns" +0ms
  electron-packager Renaming Electron to Duolingo in /Users/USER/Duolingo-darwin-x64/Electron.app/Contents/MacOS +78ms
  electron-packager Renaming Electron Helper to Duolingo Helper in /Users/USER/Duolingo-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS +2ms
  electron-packager Renaming Electron Helper (Renderer) to Duolingo Helper (Renderer) in /Users/USER/Duolingo-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper (Plugin) to Duolingo Helper (Plugin) in /Users/USER/Duolingo-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Plugin).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper (GPU) to Duolingo Helper (GPU) in /Users/USER/Duolingo-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (GPU).app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper.app to Duolingo Helper.app in /Users/USER/Duolingo-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Renderer).app to Duolingo Helper (Renderer).app in /Users/USER/Duolingo-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Plugin).app to Duolingo Helper (Plugin).app in /Users/USER/Duolingo-darwin-x64/Electron.app/Contents/Frameworks +1ms
  electron-packager Renaming Electron Helper (GPU).app to Duolingo Helper (GPU).app in /Users/USER/Duolingo-darwin-x64/Electron.app/Contents/Frameworks +0ms

Finalizing build...
App built to /Users/USER/Duolingo-darwin-x64 , move it wherever it makes sense for you and run the app bundle.
```

**Expected behavior**
Fall back to favicon/Apple touch Icon
<img src="https://d35aaqx5ub95lt.cloudfront.net/images/duolingo-touch-icon2.png" width=128/ >

**Actual behavior**
Uses incorrect icon from nativefier-icons
<img src="https://raw.githubusercontent.com/nativefier/nativefier-icons/gh-pages/files/ing.png" width=128/ >

**Debug info**

- Console logs of your `nativefier` build command, with `--verbose` flag
- If the bug happens at app run time, the in-app DevTools console logs (open it with F12)
- Error messages
- Screenshots
- Anything else relevant!

**Context**

 - Nativefier: 42.3.0
 - Node.js: v15.10.0
 - Npm: 7.6.0
 - OS: macOS 10.13.6
 - Is it a regression? If yes, what's the last working / first broken version? 
 - Additional context: (for example: "I'm behind a proxy, with configuration X and protocol Y")

**Comment by TheCleric** [comment] 2021-03-05 23:29
Potential duplicate of #969

**Comment by ronjouch** [comment] 2021-03-06 01:36
> Potential duplicate of #969

Indeed, thanks everybody. Improved name of #969 for better searchability and closing this one.

**Closed by ronjouch** 2021-03-06 01:36 UTC
Labels: bug
