### ISSUE TITLE
Google Calendar Nativefier app launches browser

### ISSUE THREAD

**Issue by dyspop** [nativefier/nativefier#673] opened 2018-08-23 12:58 UTC
### Description

I successfully Nativefied Google Calendar, but when the app successfully logs in to a Google account it launches the default browser and opens the calendar. The Google login screen hangs within the Nativefier app.

### Steps to reproduce issue

* Launch app
* Log in

### Details

- Are you nativefying a *public* website?
No
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
Yes
- Full nativefier command used to build your app: `$nativefier --name "G Cal" "https://calendar.google.com/calendar/r/"`
See above
- Version of Nativefier (run `nativefier --version`): `7.6.7`
- Version of node.js (run `node --version`): `v8.0.0`
- OS: `macOS 10.12.6`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by bacongravy** [comment] 2018-08-29 19:55
This may be a case of google redirecting to a login URL that is considered an external URL.  If this is a regression, it may have been introduced by #622, and if so, it may be possible to work around with the --internal-urls option.

**Comment by TheCleric** [comment] 2021-04-29 21:54
@dyspop since you've submitted this bug, I think we've come a long way (in terms of the `--internal-urls` flag and defaulting to keep known login pages internal. Can you confirm if you still have this issue on the current version of Nativefier?

**Comment by TheCleric** [comment] 2021-05-12 16:54
Closing as I have not heard a response back. We can reopen if anyone is still experiencing this.

**Closed by TheCleric** 2021-05-12 16:54 UTC
Labels: bug, need-info
